### ISSUE TITLE
Task1

### ISSUE THREAD

**Issue by YakutovDmitriy** [mrinalmanu/class_assignments#1]
Your implementations of `unique` and `mex` do not pass tests from here: `https://github.com/YakutovDmitriy/bio-python-course-2018/tree/master/task1`. Please fix it and test using all the sample tests.

Thanks

**Comment by mrinalmanu** [comment]
I have corrected all the functions.
Thank you.

**Comment by YakutovDmitriy** [comment]
You have several expressions like this:
```
a = print(...)
return a
```
Function `print` returns nothing, so `a` equals to `None` here and you return nothing from your function. Please fix it. Also do not print result inside of function. This is side-effect which is not expected from the user.

**Comment by mrinalmanu** [comment]
I corrected. I will remember this.

Thank you :)

**Comment by YakutovDmitriy** [comment]
Your hw is ok now!

But this will be good to remove expressions which do not make any sence, e.g:
```
    for x in y:
        if x not in output:
            output.append(x)
    output                        # this line has no effect
    return output
```
