### ISSUE TITLE
Task 2, addborder() function

### ISSUE THREAD

**Issue by mrinalmanu** [mrinalmanu/class_assignments#2]
I am working on the border problem. I think if I solve this one, I might be able to solve other similar problems as well.

**Comment by YakutovDmitriy** [comment]
Functions `listToString`, `shorting`, `competition` and `goodPairs` is ok!

General notes:
You use the following code:
```python
for i in range(len(n)):
    if len(n[i]) <= 10:
...
```
It's not necessary to know the index `i` of object `n[i]` in the list here, so you can replace this code with the following:
```python
for elem in n:
    if len(elem) <= 10:
...
```

**Comment by YakutovDmitriy** [comment]
About `makeShell`:
* `makeShell(2)` should be `[[0], [0, 0], [0]]`, not `[[[0]], [[0, 0]], [[0]]]`

**Comment by YakutovDmitriy** [comment]
About `addBorder`. Do I understand that you are trying to get the following:
```python
['+---+',
'|abc|',
'|def|',
'+---+']
```
and not the following:
```python
['+---+', '|abc|', '|def|', '+---+']
```

**Comment by mrinalmanu** [comment]
something like this:


def addborder(a):
    up_to_down = a.splitlines()
    right_to_left = max(len(x) for x in up_to_down)
    wrap = ['+','--'*right_to_left,'+']
    for x in up_to_down:
        wrap.append('|'+(x+'-'*right_to_left)[:right_to_left]+'|')
    wrap.append('+'+"'"+*right_to_left+'+')
    return wrap

**Comment by YakutovDmitriy** [comment]
Woah, you are given a list of strings, so you do not need to split `a`. Also strings in `a` have equal length

**Comment by mrinalmanu** [comment]
I think the border problem is alright!

**Comment by YakutovDmitriy** [comment]
* `addBorder`
Lets see at the sample test:
```
addBorder(['abc',
           'def']) = ['+---+',
                      '|abc|',
                      '|def|',
                      '+---+']
```
I dont know if it is obvious or not, but the result of this function is list of strings, not string. This task is simpler than you think)

**Comment by mrinalmanu** [comment]
I solved the addborder problem 👍

**Comment by mrinalmanu** [comment]
I solved the addborder problem 👍

**Comment by YakutovDmitriy** [comment]
* `addborder` -- good!
* `pep8` is good!
* `asserts` -- good!

You have to remove your `main` function. Or put it under `if __name__ == '__main__'` condition
